In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
dataset = pd.read_csv('D:/Churn_Modelling.csv')
x = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [20]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [21]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [22]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelEncoder_x_1 = LabelEncoder()
labelEncoder_x_2 = LabelEncoder()
x[:, 1] = labelEncoder_x_1.fit_transform(x[:, 1])
x[:, 2] = labelEncoder_x_2.fit_transform(x[:, 2])
oneHotEncoder = OneHotEncoder(categorical_features=[1])
x = oneHotEncoder.fit_transform(x).toarray()
x = x[:, 1:]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [23]:
x

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [26]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [27]:
classifier = Sequential()

In [28]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [29]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [30]:
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [31]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [32]:
classifier.fit(x_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 2s 292us/step - loss: 0.4819 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 2s 223us/step - loss: 0.4283 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 235us/step - loss: 0.4207 - accuracy: 0.8099
Epoch 4/100
8000/8000 [==============================] - 2s 230us/step - loss: 0.4152 - accuracy: 0.8321
Epoch 5/100
8000/8000 [==============================] - 2s 231us/step - loss: 0.4096 - accuracy: 0.8313
Epoch 6/100
8000/8000 [==============================] - 2s 252us/step - loss: 0.4075 - accuracy: 0.8317
Epoch 7/100
8000/8000 [==============================] - 2s 219us/step - loss: 0.4048 - accuracy: 0.8351
Epoch 8/100
8000/8000 [==============================] - 2s 193us/step - loss: 0.4026 - accuracy: 0.8349
Epoch 9/100
8000/8000 [==============================] - 2s 211us/step - loss: 0.4013 - accuracy: 0.8331
Epoch 10/100
8000/8000 [==============================]

In [33]:
y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)

In [34]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [35]:
cm

array([[1491,  104],
       [ 184,  221]], dtype=int64)

In [39]:
(1491 + 221)/2000

0.856