In [1]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.13.1


## Variable

In [4]:
hello_constant = tf.constant("Hello Tensorflow")

In [5]:
print(hello_constant)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    output = sess.run(hello_constant).decode()
    print(output)

Hello Tensorflow


In [8]:
var1 = tf.constant(5.5)
var2 = tf.constant(10.5)
sess = tf.Session()
out = sess.run([var1, var2])
print(out)
sess.close()

[5.5, 10.5]


In [10]:
var3 = var2*var1
sess = tf.Session()
out = sess.run(var3)
print(out)
sess.close()

57.75


In [16]:
matrix = tf.constant([[1,2,3],[4,5,6]], dtype = 'int64')
matrix

<tf.Tensor 'Const_6:0' shape=(2, 3) dtype=int64>

In [17]:
matrix = tf.constant([[1],[4], [5]], dtype = 'int64')
matrix

<tf.Tensor 'Const_7:0' shape=(3, 1) dtype=int64>

In [18]:
matrix_2 = tf.constant([[[1,2,3],[4,5,6]]])
matrix_2

<tf.Tensor 'Const_8:0' shape=(1, 2, 3) dtype=int32>

In [27]:
tf.zeros(10)
zero_mat = tf.zeros((2,2))
zero_mat

<tf.Tensor 'zeros_7:0' shape=(2, 2) dtype=float32>

In [28]:
sess = tf.Session()
sess.run(zero_mat)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [30]:
one_mat = tf.ones((2,2))
one_mat

<tf.Tensor 'ones:0' shape=(2, 2) dtype=float32>

In [31]:
sess = tf.Session()
sess.run(one_mat)

array([[1., 1.],
       [1., 1.]], dtype=float32)

## Placeholder

In [29]:
data_place = tf.placeholder(tf.float16)
print(data_place)

Tensor("Placeholder:0", dtype=float16)


In [34]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

adder = a+b
sess = tf.Session()
sess.run(adder, feed_dict={a:[[1,2,3],[1,2,3],[1,2,3]], b:[[3,3,3],[5,6,7],[4,3,3]]})

array([[ 4.,  5.,  6.],
       [ 6.,  8., 10.],
       [ 5.,  5.,  6.]], dtype=float32)

## Variable Data Type

In [36]:
w1 = tf.Variable([2.9], tf.float32)
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(w1))

[2.9]
